### ISSUE TITLE
Have a list of hackathon style definitions

### ISSUE THREAD

**Issue by DCGenomics** [biohackathons/biohackathons.github.io#1]
Metadata:  
+ Duration
+ Time per day
+ Goals
++ Data Analysis
++ Tool-building
+ Main topics
+ Frequency
+ Conference

Biohackathon
BOSC
Elixir
NCBI 
NCBI-style

**Comment by DCGenomics** [comment]
@fstrozzi can you edit the elixir section on the https://github.com/biohackathons/biohackathons.github.io/blob/master/pages/About.md
page?

**Comment by fstrozzi** [comment]
@DCGenomics Done, I've updated the BOSC and the Biohackathon too.

**Comment by DCGenomics** [comment]
Thanks @fstrozzi !
